//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eConnect.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblApplicationSetting
    {
        public int SettingId { get; set; }
        public Nullable<int> BusinessId { get; set; }
        public string ApplicationName { get; set; }
        public Nullable<bool> AutoBackUp { get; set; }
        public string AutoBackUpDuration { get; set; }
    
        public virtual tblBusiness tblBusiness { get; set; }
    }
}
