//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eConnect.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCSPDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCSPDetail()
        {
            this.tblDepositRequests = new HashSet<tblDepositRequest>();
            this.tblTechRequests = new HashSet<tblTechRequest>();
            this.tblWithdrawalRequests = new HashSet<tblWithdrawalRequest>();
        }
    
        public int CSPId { get; set; }
        public string Name { get; set; }
        public string CSPCode { get; set; }
        public string BranchCode { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public string BankName { get; set; }
        public string BankAccountNumber { get; set; }
        public string IFSC { get; set; }
        public string FatherName { get; set; }
        public string MotherName { get; set; }
        public string EmailId { get; set; }
        public string EmergencyContactNumber { get; set; }
        public string PAN { get; set; }
        public string VoterId { get; set; }
        public string AadharNo { get; set; }
        public string ProfilePicSource { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public string Education { get; set; }
        public string VoterIdSource { get; set; }
        public string PANSource { get; set; }
        public string AadharCardSource { get; set; }
        public string EducationProofSource { get; set; }
        public string IIBFCertificationSource { get; set; }
    
        public virtual tblCity tblCity { get; set; }
        public virtual tblUser tblUser { get; set; }
        public virtual tblUser tblUser1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDepositRequest> tblDepositRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTechRequest> tblTechRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblWithdrawalRequest> tblWithdrawalRequests { get; set; }
    }
}
