//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eConnect.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCommissionReport
    {
        public long CommissionReportId { get; set; }
        public Nullable<int> CSPCode { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> CommissionReportTransactionType { get; set; }
        public Nullable<long> NumberOfTransactions { get; set; }
        public Nullable<decimal> Commission { get; set; }
    
        public virtual tblCommissionReportTransactionType tblCommissionReportTransactionType { get; set; }
    }
}
