//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eConnect.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCommissionReportMain
    {
        public long TransactionCommissionId { get; set; }
        public string Circle { get; set; }
        public string CircleName { get; set; }
        public string BCBF_Code { get; set; }
        public string CSPCode { get; set; }
        public string CSPName { get; set; }
        public string TransactionType { get; set; }
        public Nullable<decimal> NoOfTransactions { get; set; }
        public Nullable<decimal> Commission { get; set; }
        public Nullable<int> UploaderId { get; set; }
    
        public virtual tblUploader tblUploader { get; set; }
    }
}
