//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eConnect.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblConfiguration
    {
        public int ConfigurationId { get; set; }
        public Nullable<int> BusinessId { get; set; }
        public Nullable<int> DeactiveAccountDaysForInvalidPwd { get; set; }
        public Nullable<int> LockAccountDaysForInvalidPwd { get; set; }
        public Nullable<int> AutoUnlockAccountMinutes { get; set; }
        public Nullable<int> PasswordAutoExpireInDays { get; set; }
        public Nullable<bool> IsPasswordNeverExpired { get; set; }
        public Nullable<bool> ChangedPwdOnNextLogin { get; set; }
        public Nullable<int> PasswordLength { get; set; }
        public Nullable<bool> NotifiedToCSP { get; set; }
    
        public virtual tblBusiness tblBusiness { get; set; }
    }
}
