//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eConnect.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFolderImageDetail
    {
        public int FolderImageId { get; set; }
        public int FolderId { get; set; }
        public int UploadedBy { get; set; }
        public System.DateTime UploadedDate { get; set; }
        public bool InActive { get; set; }
        public string ImageName { get; set; }
    
        public virtual tblFolderDetail tblFolderDetail { get; set; }
    }
}
