//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eConnect.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserCSPDetail
    {
        public int CSPId { get; set; }
        public string CSPName { get; set; }
        public string CSPCode { get; set; }
        public string BranchCode { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public string BankName { get; set; }
        public string BankAccount { get; set; }
        public string IFSC { get; set; }
        public string CertificateStatus { get; set; }
        public Nullable<int> Status { get; set; }
        public string FatherName { get; set; }
        public string MotherName { get; set; }
        public Nullable<int> Country { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<int> City { get; set; }
        public string PAN { get; set; }
        public string VoterId { get; set; }
        public string AadharNo { get; set; }
        public string Education { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string EmergencyContactNumber { get; set; }
        public string PassportSizePhoto { get; set; }
        public string VoterIdImage { get; set; }
        public string PANImage { get; set; }
        public string AadharImage { get; set; }
        public string LatestEducationProofImage { get; set; }
        public string IIBFCertificationImage { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    
        public virtual tblCity tblCity { get; set; }
        public virtual tblCountry tblCountry { get; set; }
        public virtual tblState tblState { get; set; }
        public virtual tblStatu tblStatu { get; set; }
    }
}
