//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eConnect.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWebFeedback
    {
        public int FeedbackId { get; set; }
        public string Requestor { get; set; }
        public string EmailId { get; set; }
        public string MobileNo { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> receivedOn { get; set; }
        public Nullable<bool> IsReplied { get; set; }
        public Nullable<int> RepliedBy { get; set; }
    }
}
